name: CI

on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "main" ]
  merge_group:

# You can leverage Vercel Remote Caching with Turbo to speed up your builds
# @link https://turborepo.org/docs/core-concepts/remote-caching#remote-caching-on-vercel-builds
# env:
#  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
#  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  build-lint:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16.1
        env:
          POSTGRES_USER: default
          POSTGRES_PASSWORD: default
          POSTGRES_DB: verceldb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Copy env
        shell: bash
        run: cp .env.example .env.local

      - name: Setup bun
        uses: oven-sh/setup-bun@v1

      - name: Install lib
        run: bun i

      - name: Build
        run: bun run build
        env:
          # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: postgres
          # The default PostgreSQL port
          POSTGRES_PORT: 5432
          POSTGRES_USER: default
          POSTGRES_PASSWORD: default
          POSTGRES_DB: verceldb
          POSTGRES_URL: postgres://default:default@localhost:5432/verceldb
          # Required for build
          NEXT_PUBLIC_APP_URL: 'http://localhost:3000'
          NEXTAUTH_URL: 'http://localhost:3000'
          NEXTAUTH_SECRET: 'test-secret-for-ci'
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: 'pk_test_test'
          CLERK_SECRET_KEY: 'sk_test_test'
          GITHUB_CLIENT_ID: 'test_github_client_id'
          GITHUB_CLIENT_SECRET: 'test_github_client_secret'
          RESEND_API_KEY: 'test'
          RESEND_FROM: 'test@example.com'
          STRIPE_API_KEY: 'sk_test_test'
          STRIPE_WEBHOOK_SECRET: 'whsec_test'
          NEXT_PUBLIC_STRIPE_STD_PRODUCT_ID: 'prod_test'
          NEXT_PUBLIC_STRIPE_STD_MONTHLY_PRICE_ID: 'price_test'
          NEXT_PUBLIC_STRIPE_PRO_PRODUCT_ID: 'prod_test'
          NEXT_PUBLIC_STRIPE_PRO_MONTHLY_PRICE_ID: 'price_test'
          NEXT_PUBLIC_STRIPE_PRO_YEARLY_PRICE_ID: 'price_test'
          NEXT_PUBLIC_STRIPE_BUSINESS_PRODUCT_ID: 'prod_test'
          NEXT_PUBLIC_STRIPE_BUSINESS_MONTHLY_PRICE_ID: 'price_test'
          NEXT_PUBLIC_STRIPE_BUSINESS_YEARLY_PRICE_ID: 'price_test'
          NEXT_PUBLIC_POSTHOG_KEY: 'test'
          NEXT_PUBLIC_POSTHOG_HOST: 'https://app.posthog.com'
          ADMIN_EMAIL: 'admin@test.com'
          IS_DEBUG: 'false'


      - name: lint and type-check
        run: bun run lint && bun run format && bun run typecheck
        env:
          # Database
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          POSTGRES_USER: default
          POSTGRES_PASSWORD: default
          POSTGRES_DB: verceldb
          POSTGRES_URL: postgres://default:default@localhost:5432/verceldb
          # Required for type-checking
          NEXT_PUBLIC_APP_URL: 'http://localhost:3000'
          NEXTAUTH_URL: 'http://localhost:3000'
          NEXTAUTH_SECRET: 'test-secret-for-ci'
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: 'pk_test_test'
          CLERK_SECRET_KEY: 'sk_test_test'
          GITHUB_CLIENT_ID: 'test_github_client_id'
          GITHUB_CLIENT_SECRET: 'test_github_client_secret'
          RESEND_API_KEY: 'test'
          RESEND_FROM: 'test@example.com'
          STRIPE_API_KEY: 'sk_test_test'
          STRIPE_WEBHOOK_SECRET: 'whsec_test'
          NEXT_PUBLIC_STRIPE_STD_PRODUCT_ID: 'prod_test'
          NEXT_PUBLIC_STRIPE_STD_MONTHLY_PRICE_ID: 'price_test'
          NEXT_PUBLIC_STRIPE_PRO_PRODUCT_ID: 'prod_test'
          NEXT_PUBLIC_STRIPE_PRO_MONTHLY_PRICE_ID: 'price_test'
          NEXT_PUBLIC_STRIPE_PRO_YEARLY_PRICE_ID: 'price_test'
          NEXT_PUBLIC_STRIPE_BUSINESS_PRODUCT_ID: 'prod_test'
          NEXT_PUBLIC_STRIPE_BUSINESS_MONTHLY_PRICE_ID: 'price_test'
          NEXT_PUBLIC_STRIPE_BUSINESS_YEARLY_PRICE_ID: 'price_test'
          NEXT_PUBLIC_POSTHOG_KEY: 'test'
          NEXT_PUBLIC_POSTHOG_HOST: 'https://app.posthog.com'
          ADMIN_EMAIL: 'admin@test.com'
          IS_DEBUG: 'false'
